[package]
name = "reversi_lib"
version = "0.1.0"
authors = ["umedaikiti <umedaikiti@gmail.com>"]

[lib]
name = "reversi"
path = "src/lib.rs"
crate_type = ["dylib"]

[dependencies]
reversi_ai = {path = "../reversi_ai"}
